const types = {
    SET_BLOG_ID: 'SET_BLOG_ID',
    SET_CHANGELAYOUT: 'SET_CHANGELAYOUT',
    SET_CURRENTUSER: 'SET_CURRENTUSER',
    SET_LOGIN: 'SET_LOGIN',
    SET_LOGIN_ERROR:'SET_LOGIN_ERROR',
    SET_THEME: 'SET_THEME',
    SET_FBDATOS: 'SET_FBDATOS',
    SET_LOADING: 'SET_LOADING',
    SET_TIMESTART: 'SET_TIMESTART',
    SET_TIMEEND: 'SET_TIMEEND',
    SET_TIMESTARTPAST: 'SET_TIMESTARTPAST',
    SET_TIMEENDPAST: 'SET_TIMEENDPAST',
  };
  
  export default types;
  